import assert from "node:assert/strict";
import {
  getMenuCategoryFormValues,
  getMenuOptionFormValues,
  getMenuOptionGroupFormValues,
  getMenuProductFormValues,
} from "../src/utils/menuFormValues";
import { test } from "vitest";

test("menuFormValues.test", () => {
  assert.deepEqual(getMenuProductFormValues(), {
    categoryId: "",
    key: "",
    itemType: "product",
    pricingModel: "fixed",
    name: { ar: "", en: "" },
    description: { ar: "", en: "" },
    imageUrl: "",
    priceSar: 0,
    baseUnitGrams: undefined,
    defaultWeightGrams: undefined,
    minWeightGrams: undefined,
    maxWeightGrams: undefined,
    weightStepGrams: undefined,
    weightStepPriceSar: undefined,
    useWeightStepPricing: false,
    weightPricingFormMode: "fixed",
    isActive: true,
    isAvailable: true,
    isVisible: true,
    isCustomizable: false,
    availableFor: ["one_time", "subscription"],
    ui: {
      cardSize: "medium",
    },
    sortOrder: 0,
  });

  assert.deepEqual(
    getMenuProductFormValues({
      id: "product-1",
      categoryId: { _id: "category-1" } as never,
      key: "grilled-chicken",
      itemType: "basic_meal",
      name: { ar: "دجاج", en: "Chicken" },
      description: { ar: "وصف", en: "Desc" },
      imageUrl: "https://cdn.example.com/item.jpg",
      pricingModel: "per_100g",
      priceHalala: 2500,
      baseUnitGrams: 100,
      defaultWeightGrams: 100,
      minWeightGrams: 100,
      maxWeightGrams: 300,
      weightStepGrams: 50,
      weightStepPriceHalala: 500,
      isActive: true,
      isAvailable: true,
      availableFor: ["order"],
      availableForSubscription: false,
      ui: { cardVariant: "premium", cardSize: "small", badge: "new", ctaLabel: "Buy", imageRatio: "16/9" },
      sortOrder: 8,
    } as never),
    {
      categoryId: "category-1",
      key: "grilled-chicken",
      itemType: "basic_meal",
      pricingModel: "per_100g",
      name: { ar: "دجاج", en: "Chicken" },
      description: { ar: "وصف", en: "Desc" },
      imageUrl: "https://cdn.example.com/item.jpg",
      priceSar: 25,
      baseUnitGrams: 100,
      defaultWeightGrams: 100,
      minWeightGrams: 100,
      maxWeightGrams: 300,
      weightStepGrams: 50,
      weightStepPriceSar: 5,
      useWeightStepPricing: true,
      weightPricingFormMode: "existing_modern",
      isActive: true,
      isAvailable: true,
      isVisible: true,
      isCustomizable: false,
      availableFor: ["one_time"],
      ui: {
        cardSize: "small",
      },
      sortOrder: 8,
    }
  );

  assert.deepEqual(
    getMenuProductFormValues({
      id: "product-2",
      categoryId: "" as never,
      category: { id: "category-2" } as never,
      key: "legacy-product",
      itemType: "" as never,
      type: "drink" as never,
      name: { ar: "ماء", en: "Water" },
      pricingModel: "fixed",
      priceHalala: 500,
      isActive: true,
      isAvailable: true,
      availableFor: [],
      ui: {},
      sortOrder: 1,
    } as never),
    {
      categoryId: "category-2",
      key: "legacy-product",
      itemType: "drink",
      pricingModel: "fixed",
      name: { ar: "ماء", en: "Water" },
      description: { ar: "", en: "" },
      imageUrl: "",
      priceSar: 5,
      baseUnitGrams: undefined,
      defaultWeightGrams: undefined,
      minWeightGrams: undefined,
      maxWeightGrams: undefined,
      weightStepGrams: undefined,
      weightStepPriceSar: undefined,
      useWeightStepPricing: false,
      weightPricingFormMode: "fixed",
      isActive: true,
      isAvailable: true,
      isVisible: true,
      isCustomizable: false,
      availableFor: ["one_time", "subscription"],
      ui: {
        cardSize: "medium",
      },
      sortOrder: 1,
    }
  );

  assert.deepEqual(getMenuCategoryFormValues(), {
    key: "",
    name: { ar: "", en: "" },
    description: { ar: "", en: "" },
    imageUrl: "",
    isActive: true,
    isAvailable: true,
    isVisible: true,
    sortOrder: 0,
  });

  assert.deepEqual(getMenuOptionGroupFormValues(), {
    key: "",
    name: { ar: "", en: "" },
    description: { ar: "", en: "" },
    isActive: true,
    isAvailable: true,
    isVisible: true,
    ui: { displayStyle: "chips" },
    sortOrder: 0,
  });

  assert.deepEqual(getMenuOptionFormValues(), {
    groupId: "",
    key: "",
    name: { ar: "", en: "" },
    description: { ar: "", en: "" },
    imageUrl: "",
    extraPriceSar: 0,
    extraWeightUnitGrams: undefined,
    extraWeightPriceSar: undefined,
    isActive: true,
    isAvailable: true,
    isVisible: true,
    extraFeeSar: 0,
    availableFor: ["one_time", "subscription"],
    availableForSubscription: true,
    sortOrder: 0,
  });
});
