import { ADDON_QUERY_KEYS } from "../../utils/addonPickerContract.ts";

export const MENU_PRODUCTS_QUERY_KEY = "menu.products";
export const MENU_CATEGORIES_QUERY_KEY = "menu.categories";

export const ADDON_PICKER_INVALIDATION_KEYS = [
  ADDON_QUERY_KEYS.productPicker,
  ADDON_QUERY_KEYS.categoryPicker,
];

export const MENU_PRODUCT_INVALIDATION_KEYS = [
  [MENU_PRODUCTS_QUERY_KEY],
  ...ADDON_PICKER_INVALIDATION_KEYS,
];

export const MENU_PRODUCT_AND_CATEGORY_INVALIDATION_KEYS = [
  [MENU_PRODUCTS_QUERY_KEY],
  [MENU_CATEGORIES_QUERY_KEY],
  ...ADDON_PICKER_INVALIDATION_KEYS,
];

export const MENU_CATEGORY_INVALIDATION_KEYS = [
  [MENU_CATEGORIES_QUERY_KEY],
  ...ADDON_PICKER_INVALIDATION_KEYS,
];

export const MENU_CATEGORY_AND_PRODUCT_INVALIDATION_KEYS = [
  [MENU_CATEGORIES_QUERY_KEY],
  [MENU_PRODUCTS_QUERY_KEY],
  ...ADDON_PICKER_INVALIDATION_KEYS,
];
