/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedZonesIndexRouteImport } from './routes/_protected/zones/index'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedSubscriptionsIndexRouteImport } from './routes/_protected/subscriptions/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedRestaurantHoursIndexRouteImport } from './routes/_protected/restaurant-hours/index'
import { Route as ProtectedPromoCodesIndexRouteImport } from './routes/_protected/promo-codes/index'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedPickupBranchesIndexRouteImport } from './routes/_protected/pickup-branches/index'
import { Route as ProtectedPaymentsIndexRouteImport } from './routes/_protected/payments/index'
import { Route as ProtectedPackagesIndexRouteImport } from './routes/_protected/packages/index'
import { Route as ProtectedOperationsIndexRouteImport } from './routes/_protected/operations/index'
import { Route as ProtectedOneTimeOrdersIndexRouteImport } from './routes/_protected/one-time-orders/index'
import { Route as ProtectedNotificationsIndexRouteImport } from './routes/_protected/notifications/index'
import { Route as ProtectedMenuIndexRouteImport } from './routes/_protected/menu/index'
import { Route as ProtectedManualDeductionIndexRouteImport } from './routes/_protected/manual-deduction/index'
import { Route as ProtectedDeliveryIndexRouteImport } from './routes/_protected/delivery/index'
import { Route as ProtectedDashboardUsersIndexRouteImport } from './routes/_protected/dashboard-users/index'
import { Route as ProtectedAddonsIndexRouteImport } from './routes/_protected/addons/index'
import { Route as ProtectedAccountingIndexRouteImport } from './routes/_protected/accounting/index'
import { Route as ProtectedUsersCreateRouteImport } from './routes/_protected/users/create'
import { Route as ProtectedSubscriptionsCreateRouteImport } from './routes/_protected/subscriptions/create'
import { Route as ProtectedPackagesCreateRouteImport } from './routes/_protected/packages/create'
import { Route as ProtectedOneTimeOrdersOrderIdRouteImport } from './routes/_protected/one-time-orders/$orderId'
import { Route as ProtectedAddonsCreateRouteImport } from './routes/_protected/addons/create'
import { Route as ProtectedUsersUserIdIndexRouteImport } from './routes/_protected/users/$userId/index'
import { Route as ProtectedSubscriptionsSubscriptionIdIndexRouteImport } from './routes/_protected/subscriptions/$subscriptionId/index'
import { Route as ProtectedUsersUserIdCreateSubscriptionRouteImport } from './routes/_protected/users/$userId/create-subscription'
import { Route as ProtectedPackagesPlanIdUpdateRouteImport } from './routes/_protected/packages/$planId/update'
import { Route as ProtectedMenuProductsCreateRouteImport } from './routes/_protected/menu/products/create'
import { Route as ProtectedMenuOptionsCreateRouteImport } from './routes/_protected/menu/options/create'
import { Route as ProtectedMenuOptionGroupsCreateRouteImport } from './routes/_protected/menu/option-groups/create'
import { Route as ProtectedMenuCategoriesCreateRouteImport } from './routes/_protected/menu/categories/create'
import { Route as ProtectedAddonsAddonIdUpdateRouteImport } from './routes/_protected/addons/$addonId/update'
import { Route as ProtectedMenuProductsProductIdUpdateRouteImport } from './routes/_protected/menu/products/$productId/update'
import { Route as ProtectedMenuOptionsOptionIdUpdateRouteImport } from './routes/_protected/menu/options/$optionId/update'
import { Route as ProtectedMenuOptionGroupsGroupIdUpdateRouteImport } from './routes/_protected/menu/option-groups/$groupId/update'
import { Route as ProtectedMenuCategoriesCategoryIdUpdateRouteImport } from './routes/_protected/menu/categories/$categoryId/update'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedZonesIndexRoute = ProtectedZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSubscriptionsIndexRoute =
  ProtectedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRestaurantHoursIndexRoute =
  ProtectedRestaurantHoursIndexRouteImport.update({
    id: '/restaurant-hours/',
    path: '/restaurant-hours/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPromoCodesIndexRoute =
  ProtectedPromoCodesIndexRouteImport.update({
    id: '/promo-codes/',
    path: '/promo-codes/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPickupBranchesIndexRoute =
  ProtectedPickupBranchesIndexRouteImport.update({
    id: '/pickup-branches/',
    path: '/pickup-branches/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaymentsIndexRoute = ProtectedPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPackagesIndexRoute = ProtectedPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOperationsIndexRoute =
  ProtectedOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_protected/operations/index.lazy').then((d) => d.Route),
  )
const ProtectedOneTimeOrdersIndexRoute =
  ProtectedOneTimeOrdersIndexRouteImport.update({
    id: '/one-time-orders/',
    path: '/one-time-orders/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedNotificationsIndexRoute =
  ProtectedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMenuIndexRoute = ProtectedMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedManualDeductionIndexRoute =
  ProtectedManualDeductionIndexRouteImport.update({
    id: '/manual-deduction/',
    path: '/manual-deduction/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDeliveryIndexRoute = ProtectedDeliveryIndexRouteImport.update({
  id: '/delivery/',
  path: '/delivery/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardUsersIndexRoute =
  ProtectedDashboardUsersIndexRouteImport.update({
    id: '/dashboard-users/',
    path: '/dashboard-users/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAddonsIndexRoute = ProtectedAddonsIndexRouteImport.update({
  id: '/addons/',
  path: '/addons/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAccountingIndexRoute =
  ProtectedAccountingIndexRouteImport.update({
    id: '/accounting/',
    path: '/accounting/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedUsersCreateRoute = ProtectedUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSubscriptionsCreateRoute =
  ProtectedSubscriptionsCreateRouteImport.update({
    id: '/subscriptions/create',
    path: '/subscriptions/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPackagesCreateRoute = ProtectedPackagesCreateRouteImport.update({
  id: '/packages/create',
  path: '/packages/create',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOneTimeOrdersOrderIdRoute =
  ProtectedOneTimeOrdersOrderIdRouteImport.update({
    id: '/one-time-orders/$orderId',
    path: '/one-time-orders/$orderId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAddonsCreateRoute = ProtectedAddonsCreateRouteImport.update({
  id: '/addons/create',
  path: '/addons/create',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUsersUserIdIndexRoute =
  ProtectedUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSubscriptionsSubscriptionIdIndexRoute =
  ProtectedSubscriptionsSubscriptionIdIndexRouteImport.update({
    id: '/subscriptions/$subscriptionId/',
    path: '/subscriptions/$subscriptionId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedUsersUserIdCreateSubscriptionRoute =
  ProtectedUsersUserIdCreateSubscriptionRouteImport.update({
    id: '/users/$userId/create-subscription',
    path: '/users/$userId/create-subscription',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPackagesPlanIdUpdateRoute =
  ProtectedPackagesPlanIdUpdateRouteImport.update({
    id: '/packages/$planId/update',
    path: '/packages/$planId/update',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMenuProductsCreateRoute =
  ProtectedMenuProductsCreateRouteImport.update({
    id: '/menu/products/create',
    path: '/menu/products/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMenuOptionsCreateRoute =
  ProtectedMenuOptionsCreateRouteImport.update({
    id: '/menu/options/create',
    path: '/menu/options/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMenuOptionGroupsCreateRoute =
  ProtectedMenuOptionGroupsCreateRouteImport.update({
    id: '/menu/option-groups/create',
    path: '/menu/option-groups/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMenuCategoriesCreateRoute =
  ProtectedMenuCategoriesCreateRouteImport.update({
    id: '/menu/categories/create',
    path: '/menu/categories/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAddonsAddonIdUpdateRoute =
  ProtectedAddonsAddonIdUpdateRouteImport.update({
    id: '/addons/$addonId/update',
    path: '/addons/$addonId/update',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMenuProductsProductIdUpdateRoute =
  ProtectedMenuProductsProductIdUpdateRouteImport.update({
    id: '/menu/products/$productId/update',
    path: '/menu/products/$productId/update',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMenuOptionsOptionIdUpdateRoute =
  ProtectedMenuOptionsOptionIdUpdateRouteImport.update({
    id: '/menu/options/$optionId/update',
    path: '/menu/options/$optionId/update',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMenuOptionGroupsGroupIdUpdateRoute =
  ProtectedMenuOptionGroupsGroupIdUpdateRouteImport.update({
    id: '/menu/option-groups/$groupId/update',
    path: '/menu/option-groups/$groupId/update',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedMenuCategoriesCategoryIdUpdateRoute =
  ProtectedMenuCategoriesCategoryIdUpdateRouteImport.update({
    id: '/menu/categories/$categoryId/update',
    path: '/menu/categories/$categoryId/update',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/addons/create': typeof ProtectedAddonsCreateRoute
  '/one-time-orders/$orderId': typeof ProtectedOneTimeOrdersOrderIdRoute
  '/packages/create': typeof ProtectedPackagesCreateRoute
  '/subscriptions/create': typeof ProtectedSubscriptionsCreateRoute
  '/users/create': typeof ProtectedUsersCreateRoute
  '/accounting/': typeof ProtectedAccountingIndexRoute
  '/addons/': typeof ProtectedAddonsIndexRoute
  '/dashboard-users/': typeof ProtectedDashboardUsersIndexRoute
  '/delivery/': typeof ProtectedDeliveryIndexRoute
  '/manual-deduction/': typeof ProtectedManualDeductionIndexRoute
  '/menu/': typeof ProtectedMenuIndexRoute
  '/notifications/': typeof ProtectedNotificationsIndexRoute
  '/one-time-orders/': typeof ProtectedOneTimeOrdersIndexRoute
  '/operations/': typeof ProtectedOperationsIndexRoute
  '/packages/': typeof ProtectedPackagesIndexRoute
  '/payments/': typeof ProtectedPaymentsIndexRoute
  '/pickup-branches/': typeof ProtectedPickupBranchesIndexRoute
  '/profile/': typeof ProtectedProfileIndexRoute
  '/promo-codes/': typeof ProtectedPromoCodesIndexRoute
  '/restaurant-hours/': typeof ProtectedRestaurantHoursIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/subscriptions/': typeof ProtectedSubscriptionsIndexRoute
  '/users/': typeof ProtectedUsersIndexRoute
  '/zones/': typeof ProtectedZonesIndexRoute
  '/addons/$addonId/update': typeof ProtectedAddonsAddonIdUpdateRoute
  '/menu/categories/create': typeof ProtectedMenuCategoriesCreateRoute
  '/menu/option-groups/create': typeof ProtectedMenuOptionGroupsCreateRoute
  '/menu/options/create': typeof ProtectedMenuOptionsCreateRoute
  '/menu/products/create': typeof ProtectedMenuProductsCreateRoute
  '/packages/$planId/update': typeof ProtectedPackagesPlanIdUpdateRoute
  '/users/$userId/create-subscription': typeof ProtectedUsersUserIdCreateSubscriptionRoute
  '/subscriptions/$subscriptionId/': typeof ProtectedSubscriptionsSubscriptionIdIndexRoute
  '/users/$userId/': typeof ProtectedUsersUserIdIndexRoute
  '/menu/categories/$categoryId/update': typeof ProtectedMenuCategoriesCategoryIdUpdateRoute
  '/menu/option-groups/$groupId/update': typeof ProtectedMenuOptionGroupsGroupIdUpdateRoute
  '/menu/options/$optionId/update': typeof ProtectedMenuOptionsOptionIdUpdateRoute
  '/menu/products/$productId/update': typeof ProtectedMenuProductsProductIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/addons/create': typeof ProtectedAddonsCreateRoute
  '/one-time-orders/$orderId': typeof ProtectedOneTimeOrdersOrderIdRoute
  '/packages/create': typeof ProtectedPackagesCreateRoute
  '/subscriptions/create': typeof ProtectedSubscriptionsCreateRoute
  '/users/create': typeof ProtectedUsersCreateRoute
  '/accounting': typeof ProtectedAccountingIndexRoute
  '/addons': typeof ProtectedAddonsIndexRoute
  '/dashboard-users': typeof ProtectedDashboardUsersIndexRoute
  '/delivery': typeof ProtectedDeliveryIndexRoute
  '/manual-deduction': typeof ProtectedManualDeductionIndexRoute
  '/menu': typeof ProtectedMenuIndexRoute
  '/notifications': typeof ProtectedNotificationsIndexRoute
  '/one-time-orders': typeof ProtectedOneTimeOrdersIndexRoute
  '/operations': typeof ProtectedOperationsIndexRoute
  '/packages': typeof ProtectedPackagesIndexRoute
  '/payments': typeof ProtectedPaymentsIndexRoute
  '/pickup-branches': typeof ProtectedPickupBranchesIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/promo-codes': typeof ProtectedPromoCodesIndexRoute
  '/restaurant-hours': typeof ProtectedRestaurantHoursIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/subscriptions': typeof ProtectedSubscriptionsIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/zones': typeof ProtectedZonesIndexRoute
  '/addons/$addonId/update': typeof ProtectedAddonsAddonIdUpdateRoute
  '/menu/categories/create': typeof ProtectedMenuCategoriesCreateRoute
  '/menu/option-groups/create': typeof ProtectedMenuOptionGroupsCreateRoute
  '/menu/options/create': typeof ProtectedMenuOptionsCreateRoute
  '/menu/products/create': typeof ProtectedMenuProductsCreateRoute
  '/packages/$planId/update': typeof ProtectedPackagesPlanIdUpdateRoute
  '/users/$userId/create-subscription': typeof ProtectedUsersUserIdCreateSubscriptionRoute
  '/subscriptions/$subscriptionId': typeof ProtectedSubscriptionsSubscriptionIdIndexRoute
  '/users/$userId': typeof ProtectedUsersUserIdIndexRoute
  '/menu/categories/$categoryId/update': typeof ProtectedMenuCategoriesCategoryIdUpdateRoute
  '/menu/option-groups/$groupId/update': typeof ProtectedMenuOptionGroupsGroupIdUpdateRoute
  '/menu/options/$optionId/update': typeof ProtectedMenuOptionsOptionIdUpdateRoute
  '/menu/products/$productId/update': typeof ProtectedMenuProductsProductIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/addons/create': typeof ProtectedAddonsCreateRoute
  '/_protected/one-time-orders/$orderId': typeof ProtectedOneTimeOrdersOrderIdRoute
  '/_protected/packages/create': typeof ProtectedPackagesCreateRoute
  '/_protected/subscriptions/create': typeof ProtectedSubscriptionsCreateRoute
  '/_protected/users/create': typeof ProtectedUsersCreateRoute
  '/_protected/accounting/': typeof ProtectedAccountingIndexRoute
  '/_protected/addons/': typeof ProtectedAddonsIndexRoute
  '/_protected/dashboard-users/': typeof ProtectedDashboardUsersIndexRoute
  '/_protected/delivery/': typeof ProtectedDeliveryIndexRoute
  '/_protected/manual-deduction/': typeof ProtectedManualDeductionIndexRoute
  '/_protected/menu/': typeof ProtectedMenuIndexRoute
  '/_protected/notifications/': typeof ProtectedNotificationsIndexRoute
  '/_protected/one-time-orders/': typeof ProtectedOneTimeOrdersIndexRoute
  '/_protected/operations/': typeof ProtectedOperationsIndexRoute
  '/_protected/packages/': typeof ProtectedPackagesIndexRoute
  '/_protected/payments/': typeof ProtectedPaymentsIndexRoute
  '/_protected/pickup-branches/': typeof ProtectedPickupBranchesIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_protected/promo-codes/': typeof ProtectedPromoCodesIndexRoute
  '/_protected/restaurant-hours/': typeof ProtectedRestaurantHoursIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/subscriptions/': typeof ProtectedSubscriptionsIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
  '/_protected/zones/': typeof ProtectedZonesIndexRoute
  '/_protected/addons/$addonId/update': typeof ProtectedAddonsAddonIdUpdateRoute
  '/_protected/menu/categories/create': typeof ProtectedMenuCategoriesCreateRoute
  '/_protected/menu/option-groups/create': typeof ProtectedMenuOptionGroupsCreateRoute
  '/_protected/menu/options/create': typeof ProtectedMenuOptionsCreateRoute
  '/_protected/menu/products/create': typeof ProtectedMenuProductsCreateRoute
  '/_protected/packages/$planId/update': typeof ProtectedPackagesPlanIdUpdateRoute
  '/_protected/users/$userId/create-subscription': typeof ProtectedUsersUserIdCreateSubscriptionRoute
  '/_protected/subscriptions/$subscriptionId/': typeof ProtectedSubscriptionsSubscriptionIdIndexRoute
  '/_protected/users/$userId/': typeof ProtectedUsersUserIdIndexRoute
  '/_protected/menu/categories/$categoryId/update': typeof ProtectedMenuCategoriesCategoryIdUpdateRoute
  '/_protected/menu/option-groups/$groupId/update': typeof ProtectedMenuOptionGroupsGroupIdUpdateRoute
  '/_protected/menu/options/$optionId/update': typeof ProtectedMenuOptionsOptionIdUpdateRoute
  '/_protected/menu/products/$productId/update': typeof ProtectedMenuProductsProductIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/addons/create'
    | '/one-time-orders/$orderId'
    | '/packages/create'
    | '/subscriptions/create'
    | '/users/create'
    | '/accounting/'
    | '/addons/'
    | '/dashboard-users/'
    | '/delivery/'
    | '/manual-deduction/'
    | '/menu/'
    | '/notifications/'
    | '/one-time-orders/'
    | '/operations/'
    | '/packages/'
    | '/payments/'
    | '/pickup-branches/'
    | '/profile/'
    | '/promo-codes/'
    | '/restaurant-hours/'
    | '/settings/'
    | '/subscriptions/'
    | '/users/'
    | '/zones/'
    | '/addons/$addonId/update'
    | '/menu/categories/create'
    | '/menu/option-groups/create'
    | '/menu/options/create'
    | '/menu/products/create'
    | '/packages/$planId/update'
    | '/users/$userId/create-subscription'
    | '/subscriptions/$subscriptionId/'
    | '/users/$userId/'
    | '/menu/categories/$categoryId/update'
    | '/menu/option-groups/$groupId/update'
    | '/menu/options/$optionId/update'
    | '/menu/products/$productId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/addons/create'
    | '/one-time-orders/$orderId'
    | '/packages/create'
    | '/subscriptions/create'
    | '/users/create'
    | '/accounting'
    | '/addons'
    | '/dashboard-users'
    | '/delivery'
    | '/manual-deduction'
    | '/menu'
    | '/notifications'
    | '/one-time-orders'
    | '/operations'
    | '/packages'
    | '/payments'
    | '/pickup-branches'
    | '/profile'
    | '/promo-codes'
    | '/restaurant-hours'
    | '/settings'
    | '/subscriptions'
    | '/users'
    | '/zones'
    | '/addons/$addonId/update'
    | '/menu/categories/create'
    | '/menu/option-groups/create'
    | '/menu/options/create'
    | '/menu/products/create'
    | '/packages/$planId/update'
    | '/users/$userId/create-subscription'
    | '/subscriptions/$subscriptionId'
    | '/users/$userId'
    | '/menu/categories/$categoryId/update'
    | '/menu/option-groups/$groupId/update'
    | '/menu/options/$optionId/update'
    | '/menu/products/$productId/update'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/_protected/addons/create'
    | '/_protected/one-time-orders/$orderId'
    | '/_protected/packages/create'
    | '/_protected/subscriptions/create'
    | '/_protected/users/create'
    | '/_protected/accounting/'
    | '/_protected/addons/'
    | '/_protected/dashboard-users/'
    | '/_protected/delivery/'
    | '/_protected/manual-deduction/'
    | '/_protected/menu/'
    | '/_protected/notifications/'
    | '/_protected/one-time-orders/'
    | '/_protected/operations/'
    | '/_protected/packages/'
    | '/_protected/payments/'
    | '/_protected/pickup-branches/'
    | '/_protected/profile/'
    | '/_protected/promo-codes/'
    | '/_protected/restaurant-hours/'
    | '/_protected/settings/'
    | '/_protected/subscriptions/'
    | '/_protected/users/'
    | '/_protected/zones/'
    | '/_protected/addons/$addonId/update'
    | '/_protected/menu/categories/create'
    | '/_protected/menu/option-groups/create'
    | '/_protected/menu/options/create'
    | '/_protected/menu/products/create'
    | '/_protected/packages/$planId/update'
    | '/_protected/users/$userId/create-subscription'
    | '/_protected/subscriptions/$subscriptionId/'
    | '/_protected/users/$userId/'
    | '/_protected/menu/categories/$categoryId/update'
    | '/_protected/menu/option-groups/$groupId/update'
    | '/_protected/menu/options/$optionId/update'
    | '/_protected/menu/products/$productId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/zones/': {
      id: '/_protected/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof ProtectedZonesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/subscriptions/': {
      id: '/_protected/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof ProtectedSubscriptionsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/restaurant-hours/': {
      id: '/_protected/restaurant-hours/'
      path: '/restaurant-hours'
      fullPath: '/restaurant-hours/'
      preLoaderRoute: typeof ProtectedRestaurantHoursIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/promo-codes/': {
      id: '/_protected/promo-codes/'
      path: '/promo-codes'
      fullPath: '/promo-codes/'
      preLoaderRoute: typeof ProtectedPromoCodesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/pickup-branches/': {
      id: '/_protected/pickup-branches/'
      path: '/pickup-branches'
      fullPath: '/pickup-branches/'
      preLoaderRoute: typeof ProtectedPickupBranchesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/payments/': {
      id: '/_protected/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof ProtectedPaymentsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/packages/': {
      id: '/_protected/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof ProtectedPackagesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operations/': {
      id: '/_protected/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof ProtectedOperationsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/one-time-orders/': {
      id: '/_protected/one-time-orders/'
      path: '/one-time-orders'
      fullPath: '/one-time-orders/'
      preLoaderRoute: typeof ProtectedOneTimeOrdersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/notifications/': {
      id: '/_protected/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof ProtectedNotificationsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/menu/': {
      id: '/_protected/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof ProtectedMenuIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manual-deduction/': {
      id: '/_protected/manual-deduction/'
      path: '/manual-deduction'
      fullPath: '/manual-deduction/'
      preLoaderRoute: typeof ProtectedManualDeductionIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/delivery/': {
      id: '/_protected/delivery/'
      path: '/delivery'
      fullPath: '/delivery/'
      preLoaderRoute: typeof ProtectedDeliveryIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard-users/': {
      id: '/_protected/dashboard-users/'
      path: '/dashboard-users'
      fullPath: '/dashboard-users/'
      preLoaderRoute: typeof ProtectedDashboardUsersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/addons/': {
      id: '/_protected/addons/'
      path: '/addons'
      fullPath: '/addons/'
      preLoaderRoute: typeof ProtectedAddonsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/accounting/': {
      id: '/_protected/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof ProtectedAccountingIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/users/create': {
      id: '/_protected/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof ProtectedUsersCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/subscriptions/create': {
      id: '/_protected/subscriptions/create'
      path: '/subscriptions/create'
      fullPath: '/subscriptions/create'
      preLoaderRoute: typeof ProtectedSubscriptionsCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/packages/create': {
      id: '/_protected/packages/create'
      path: '/packages/create'
      fullPath: '/packages/create'
      preLoaderRoute: typeof ProtectedPackagesCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/one-time-orders/$orderId': {
      id: '/_protected/one-time-orders/$orderId'
      path: '/one-time-orders/$orderId'
      fullPath: '/one-time-orders/$orderId'
      preLoaderRoute: typeof ProtectedOneTimeOrdersOrderIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/addons/create': {
      id: '/_protected/addons/create'
      path: '/addons/create'
      fullPath: '/addons/create'
      preLoaderRoute: typeof ProtectedAddonsCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/users/$userId/': {
      id: '/_protected/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof ProtectedUsersUserIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/subscriptions/$subscriptionId/': {
      id: '/_protected/subscriptions/$subscriptionId/'
      path: '/subscriptions/$subscriptionId'
      fullPath: '/subscriptions/$subscriptionId/'
      preLoaderRoute: typeof ProtectedSubscriptionsSubscriptionIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/users/$userId/create-subscription': {
      id: '/_protected/users/$userId/create-subscription'
      path: '/users/$userId/create-subscription'
      fullPath: '/users/$userId/create-subscription'
      preLoaderRoute: typeof ProtectedUsersUserIdCreateSubscriptionRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/packages/$planId/update': {
      id: '/_protected/packages/$planId/update'
      path: '/packages/$planId/update'
      fullPath: '/packages/$planId/update'
      preLoaderRoute: typeof ProtectedPackagesPlanIdUpdateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/menu/products/create': {
      id: '/_protected/menu/products/create'
      path: '/menu/products/create'
      fullPath: '/menu/products/create'
      preLoaderRoute: typeof ProtectedMenuProductsCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/menu/options/create': {
      id: '/_protected/menu/options/create'
      path: '/menu/options/create'
      fullPath: '/menu/options/create'
      preLoaderRoute: typeof ProtectedMenuOptionsCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/menu/option-groups/create': {
      id: '/_protected/menu/option-groups/create'
      path: '/menu/option-groups/create'
      fullPath: '/menu/option-groups/create'
      preLoaderRoute: typeof ProtectedMenuOptionGroupsCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/menu/categories/create': {
      id: '/_protected/menu/categories/create'
      path: '/menu/categories/create'
      fullPath: '/menu/categories/create'
      preLoaderRoute: typeof ProtectedMenuCategoriesCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/addons/$addonId/update': {
      id: '/_protected/addons/$addonId/update'
      path: '/addons/$addonId/update'
      fullPath: '/addons/$addonId/update'
      preLoaderRoute: typeof ProtectedAddonsAddonIdUpdateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/menu/products/$productId/update': {
      id: '/_protected/menu/products/$productId/update'
      path: '/menu/products/$productId/update'
      fullPath: '/menu/products/$productId/update'
      preLoaderRoute: typeof ProtectedMenuProductsProductIdUpdateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/menu/options/$optionId/update': {
      id: '/_protected/menu/options/$optionId/update'
      path: '/menu/options/$optionId/update'
      fullPath: '/menu/options/$optionId/update'
      preLoaderRoute: typeof ProtectedMenuOptionsOptionIdUpdateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/menu/option-groups/$groupId/update': {
      id: '/_protected/menu/option-groups/$groupId/update'
      path: '/menu/option-groups/$groupId/update'
      fullPath: '/menu/option-groups/$groupId/update'
      preLoaderRoute: typeof ProtectedMenuOptionGroupsGroupIdUpdateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/menu/categories/$categoryId/update': {
      id: '/_protected/menu/categories/$categoryId/update'
      path: '/menu/categories/$categoryId/update'
      fullPath: '/menu/categories/$categoryId/update'
      preLoaderRoute: typeof ProtectedMenuCategoriesCategoryIdUpdateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedAddonsCreateRoute: typeof ProtectedAddonsCreateRoute
  ProtectedOneTimeOrdersOrderIdRoute: typeof ProtectedOneTimeOrdersOrderIdRoute
  ProtectedPackagesCreateRoute: typeof ProtectedPackagesCreateRoute
  ProtectedSubscriptionsCreateRoute: typeof ProtectedSubscriptionsCreateRoute
  ProtectedUsersCreateRoute: typeof ProtectedUsersCreateRoute
  ProtectedAccountingIndexRoute: typeof ProtectedAccountingIndexRoute
  ProtectedAddonsIndexRoute: typeof ProtectedAddonsIndexRoute
  ProtectedDashboardUsersIndexRoute: typeof ProtectedDashboardUsersIndexRoute
  ProtectedDeliveryIndexRoute: typeof ProtectedDeliveryIndexRoute
  ProtectedManualDeductionIndexRoute: typeof ProtectedManualDeductionIndexRoute
  ProtectedMenuIndexRoute: typeof ProtectedMenuIndexRoute
  ProtectedNotificationsIndexRoute: typeof ProtectedNotificationsIndexRoute
  ProtectedOneTimeOrdersIndexRoute: typeof ProtectedOneTimeOrdersIndexRoute
  ProtectedOperationsIndexRoute: typeof ProtectedOperationsIndexRoute
  ProtectedPackagesIndexRoute: typeof ProtectedPackagesIndexRoute
  ProtectedPaymentsIndexRoute: typeof ProtectedPaymentsIndexRoute
  ProtectedPickupBranchesIndexRoute: typeof ProtectedPickupBranchesIndexRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
  ProtectedPromoCodesIndexRoute: typeof ProtectedPromoCodesIndexRoute
  ProtectedRestaurantHoursIndexRoute: typeof ProtectedRestaurantHoursIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedSubscriptionsIndexRoute: typeof ProtectedSubscriptionsIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
  ProtectedZonesIndexRoute: typeof ProtectedZonesIndexRoute
  ProtectedAddonsAddonIdUpdateRoute: typeof ProtectedAddonsAddonIdUpdateRoute
  ProtectedMenuCategoriesCreateRoute: typeof ProtectedMenuCategoriesCreateRoute
  ProtectedMenuOptionGroupsCreateRoute: typeof ProtectedMenuOptionGroupsCreateRoute
  ProtectedMenuOptionsCreateRoute: typeof ProtectedMenuOptionsCreateRoute
  ProtectedMenuProductsCreateRoute: typeof ProtectedMenuProductsCreateRoute
  ProtectedPackagesPlanIdUpdateRoute: typeof ProtectedPackagesPlanIdUpdateRoute
  ProtectedUsersUserIdCreateSubscriptionRoute: typeof ProtectedUsersUserIdCreateSubscriptionRoute
  ProtectedSubscriptionsSubscriptionIdIndexRoute: typeof ProtectedSubscriptionsSubscriptionIdIndexRoute
  ProtectedUsersUserIdIndexRoute: typeof ProtectedUsersUserIdIndexRoute
  ProtectedMenuCategoriesCategoryIdUpdateRoute: typeof ProtectedMenuCategoriesCategoryIdUpdateRoute
  ProtectedMenuOptionGroupsGroupIdUpdateRoute: typeof ProtectedMenuOptionGroupsGroupIdUpdateRoute
  ProtectedMenuOptionsOptionIdUpdateRoute: typeof ProtectedMenuOptionsOptionIdUpdateRoute
  ProtectedMenuProductsProductIdUpdateRoute: typeof ProtectedMenuProductsProductIdUpdateRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedAddonsCreateRoute: ProtectedAddonsCreateRoute,
  ProtectedOneTimeOrdersOrderIdRoute: ProtectedOneTimeOrdersOrderIdRoute,
  ProtectedPackagesCreateRoute: ProtectedPackagesCreateRoute,
  ProtectedSubscriptionsCreateRoute: ProtectedSubscriptionsCreateRoute,
  ProtectedUsersCreateRoute: ProtectedUsersCreateRoute,
  ProtectedAccountingIndexRoute: ProtectedAccountingIndexRoute,
  ProtectedAddonsIndexRoute: ProtectedAddonsIndexRoute,
  ProtectedDashboardUsersIndexRoute: ProtectedDashboardUsersIndexRoute,
  ProtectedDeliveryIndexRoute: ProtectedDeliveryIndexRoute,
  ProtectedManualDeductionIndexRoute: ProtectedManualDeductionIndexRoute,
  ProtectedMenuIndexRoute: ProtectedMenuIndexRoute,
  ProtectedNotificationsIndexRoute: ProtectedNotificationsIndexRoute,
  ProtectedOneTimeOrdersIndexRoute: ProtectedOneTimeOrdersIndexRoute,
  ProtectedOperationsIndexRoute: ProtectedOperationsIndexRoute,
  ProtectedPackagesIndexRoute: ProtectedPackagesIndexRoute,
  ProtectedPaymentsIndexRoute: ProtectedPaymentsIndexRoute,
  ProtectedPickupBranchesIndexRoute: ProtectedPickupBranchesIndexRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
  ProtectedPromoCodesIndexRoute: ProtectedPromoCodesIndexRoute,
  ProtectedRestaurantHoursIndexRoute: ProtectedRestaurantHoursIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedSubscriptionsIndexRoute: ProtectedSubscriptionsIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
  ProtectedZonesIndexRoute: ProtectedZonesIndexRoute,
  ProtectedAddonsAddonIdUpdateRoute: ProtectedAddonsAddonIdUpdateRoute,
  ProtectedMenuCategoriesCreateRoute: ProtectedMenuCategoriesCreateRoute,
  ProtectedMenuOptionGroupsCreateRoute: ProtectedMenuOptionGroupsCreateRoute,
  ProtectedMenuOptionsCreateRoute: ProtectedMenuOptionsCreateRoute,
  ProtectedMenuProductsCreateRoute: ProtectedMenuProductsCreateRoute,
  ProtectedPackagesPlanIdUpdateRoute: ProtectedPackagesPlanIdUpdateRoute,
  ProtectedUsersUserIdCreateSubscriptionRoute:
    ProtectedUsersUserIdCreateSubscriptionRoute,
  ProtectedSubscriptionsSubscriptionIdIndexRoute:
    ProtectedSubscriptionsSubscriptionIdIndexRoute,
  ProtectedUsersUserIdIndexRoute: ProtectedUsersUserIdIndexRoute,
  ProtectedMenuCategoriesCategoryIdUpdateRoute:
    ProtectedMenuCategoriesCategoryIdUpdateRoute,
  ProtectedMenuOptionGroupsGroupIdUpdateRoute:
    ProtectedMenuOptionGroupsGroupIdUpdateRoute,
  ProtectedMenuOptionsOptionIdUpdateRoute:
    ProtectedMenuOptionsOptionIdUpdateRoute,
  ProtectedMenuProductsProductIdUpdateRoute:
    ProtectedMenuProductsProductIdUpdateRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
